apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-app-new
spec:
  rules:
  - host: "python-app.test.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: python-app-new
            port:
              number: 5000